version: "3.8"
services:
  publicpostgres:
    image: postgres:9.5
    container_name: postgres-container
    ports:
        - "5432:5432"
    environment:
        POSTGRES_PASSWORD: rootPassword
        POSTGRES_USER: postgres
        PGDATA: /var/lib/postgresql/data/pgdata
        POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
        - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: