version: '3.1'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongousername
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: always
    ports:
      - 27017:27017
    volumes:
        - ./data:/data/db
    networks:
      - mongo-compose-network
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    restart: always
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongousername
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://mongousername:password@mongo:27017/
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge
