version: "3.8"
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    ports:
        - "3306:3306"
    environment:
        MARIADB_ROOT_PASSWORD: rootPassword
    volumes:
        - D:\softwares\mariadb\data:/var/lib/mysql